### ISSUE TITLE
Train Wrong

### ISSUE THREAD

**Issue by szh-1598** [sergeyprokudin/smplpix#17]
Traceback (most recent call last):
  File "D:\Users\17718\Desktop\smplpix-main\build\lib\smplpix\train.py", line 129, in <module>
    main()
  File "D:\Users\17718\Desktop\smplpix-main\build\lib\smplpix\train.py", line 64, in main
    train_dir = os.path.join(args.data_dir, 'train')
  File "C:\Users\17718\.conda\envs\py\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by sergeyprokudin** [comment]
Hi @szh-1598,

please try to run [the Colab notebook](https://colab.research.google.com/github/sergeyprokudin/smplpix/blob/main/colab_notebooks/SMPLpix_training.ipynb) and adapt the code from there for your data.

~Sergey

**Comment by szh-1598** [comment]
I have solved this problem,thank you.
