### ISSUE TITLE
Value error while training the mdoel

### ISSUE THREAD

**Issue by Alwinseb01** [sergeyprokudin/smplpix#20]
Hey there! While running the script to train the model on demo dataset, I'm facing a value error:

Traceback (most recent call last):
  File "smplpix/train.py", line 129, in <module>
    main()
  File "smplpix/train.py", line 112, in main
    init_lr=args.learning_rate)
  File "/usr/local/lib/python3.7/dist-packages/smplpix-1.0-py3.7.egg/smplpix/training.py", line 30, in train
    for batch_idx, (x, ytrue, img_names) in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/smplpix-1.0-py3.7.egg/smplpix/dataset.py", line 96, in __getitem__
    x, y = self._augment_images(x, y)
  File "/usr/local/lib/python3.7/dist-packages/smplpix-1.0-py3.7.egg/smplpix/dataset.py", line 77, in _augment_images
    shear=0, fill=self.input_fill_color)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py", line 1204, in affine
    return F_pil.affine(img, matrix=matrix, interpolation=pil_interpolation, fill=fill)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional_pil.py", line 326, in affine
    opts = _parse_fill(fill, img)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional_pil.py", line 309, in _parse_fill
    fill = int(fill)
ValueError: invalid literal for int() with base 10: 'white'

Any help regarding the same would be highly appreciated. Thanks!

**Comment by sergeyprokudin** [comment]
Hi @Alwinseb01, should be fixed now. Seems like [tvf.affine](http://pytorch.org/vision/main/generated/torchvision.transforms.functional.affine.html) used for dataset augmentation doesn't take string colour values as input anymore.

**Comment by Alwinseb01** [comment]
Thank you!
