### ISSUE TITLE
Runtime error while training for a custom video

### ISSUE THREAD

**Issue by Alwinseb01** [sergeyprokudin/smplpix#21]
Hey, I was trying to train the model using a custom dataset generated from my video and I'm getting this runtime error 

starting training...
/usr/local/lib/python3.7/dist-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/usr/local/lib/python3.7/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth
100% 528M/528M [00:55<00:00, 9.98MB/s]
  0% 0/50 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "smplpix/train.py", line 129, in <module>
    main()
  File "smplpix/train.py", line 112, in main
    init_lr=args.learning_rate)
  File "/usr/local/lib/python3.7/dist-packages/smplpix-1.0-py3.7.egg/smplpix/training.py", line 30, in train
    for batch_idx, (x, ytrue, img_names) in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 175, in default_collate
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 175, in <listcomp>
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 141, in default_collate
    **return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 270, 300] at entry 0 and [3, 149, 84] at entry 1**

Any specific reason behind it?

**Comment by sergeyprokudin** [comment]
Hi @Alwinseb01, seems like your images in the input\output folders are of a different size. If that is the case, you should adjust the dataloader so that it rescales everything to one size.

**Comment by Alwinseb01** [comment]
I'm sorry I'm a beginner here, could you please tell me how exactly should I adjust it?

**Comment by sergeyprokudin** [comment]
@Alwinseb01 you need to call smthg like [resize](https://pytorch.org/vision/stable/generated/torchvision.transforms.Resize.html#torchvision.transforms.Resize) right after you load the images [here](https://github.com/sergeyprokudin/smplpix/blob/0a55869a22c28364b8cf741c427ed96a3d4502b2/smplpix/dataset.py#L91).

**Comment by Alwinseb01** [comment]
Thank you! I'll try it out
