### ISSUE TITLE
TypeError: affine() got an unexpected keyword argument 'fill'

### ISSUE THREAD

**Issue by mrlihellohorld** [sergeyprokudin/smplpix#7]
ARGUMENTS:
Namespace(aug_prob=0.8, batch_size=4, checkpoint_path=None, data_dir='/smpl/m面部表情驱动/smplpix_data', data_url=None, device='cuda', downsample_factor=4, eval_every_nth_epoch=10, learning_rate=0.001, n_epochs=500, n_input_channels=3, n_output_channels=3, n_unet_blocks=5, resume_training=False, save_target=1, sched_patience=3, workdir='/content/smplpix_logs2/')
defining the neural renderer model (U-Net)...
starting training from scratch, cleaning the log dirs...
starting training...
  0%|                                                                                                                                                                                       | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "smplpix/train.py", line 127, in <module>
    main()
  File "smplpix/train.py", line 110, in main
    init_lr=args.learning_rate)
  File "/opt/conda/lib/python3.7/site-packages/smplpix-1.0-py3.7.egg/smplpix/training.py", line 30, in train
    for batch_idx, (x, ytrue, img_names) in enumerate(train_dataloader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/smplpix-1.0-py3.7.egg/smplpix/dataset.py", line 96, in __getitem__
    x, y = self._augment_images(x, y)
  File "/opt/conda/lib/python3.7/site-packages/smplpix-1.0-py3.7.egg/smplpix/dataset.py", line 77, in _augment_images
    shear=0, fill=self.input_fill_color)
TypeError: affine() got an unexpected keyword argument 'fill'

**Comment by sergeyprokudin** [comment]
Hi @mrlihellohorld,

This is likely a problem with your PyTorch version. Please make sure you're using up-to-date **torch** and **torchvision** packages. You can also try [the Colab training demo ](https://colab.research.google.com/github/sergeyprokudin/smplpix/blob/main/colab_notebooks/SMPLpix_training.ipynb) to check the actual versions.

Cheers,
~Sergey
